### ISSUE TITLE
Agregar la seccion de tecnologias y cambiar el lado el mensaje de comunicacion

### ISSUE THREAD

**Issue by LucasIzetta** [mamanidario19/portfolio-template#1]
Hola Dario! soy Lucas Zambrano, vengo a realizar la tarea del progama PILIS 
practica con Issue y Pull Request
Saludos.👍

**Comment by mamanidario19** [comment]
Buen día Lucas, ahora en este momento acabo de finalizar mi parte, ahora aceptare tu Pull Request
